#! /usr/bin/env bash
echo "====create-VPC==="
# if [ -z "$1" ]; then
#     echo "no VPC NAME given."
#     exit 1
# fi
VPC_NAME="my-vpc-3"
CIDR_BLOCK="172.1.0.0/16"
CIDR_BLOCK_FOR_SUBNET="172.1.0.0/20"
# create our vpc
VPC_ID=$(aws ec2 create-vpc --cidr-block "$CIDR_BLOCK" \
--region ca-central-1 \
--tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=$VPC_NAME}]" \
--query Vpc.VpcId \
--output text)

echo "VPC ID is $VPC_ID"

# Configure the VPC to enable dns-hostnames
aws ec2 modify-vpc-attribute \
    --vpc-id $VPC_ID \
    --enable-dns-hostnames
echo "Enabled dns hostname"



# create IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text
)

echo "IGW ID is $IGW_ID"
# attach the IGW
aws ec2 attach-internet-gateway \
--internet-gateway-id "$IGW_ID" \
--vpc-id "$VPC_ID"

echo "IGW Attached" 
# create subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block $CIDR_BLOCK_FOR_SUBNET \
--query Subnet.SubnetId \
--output text
)
echo "SubnetId is $SUBNET_ID"
# auto assign ipv4
aws ec2 modify-subnet-attribute \
    --subnet-id $SUBNET_ID \
    --map-public-ip-on-launch

# Get the route table
ROUTE_TABLE_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" \
"Name=association.main,Values=true" \
--query "RouteTables[].RouteTableId" \
--output text
)
echo "route table id $ROUTE_TABLE_ID"
# Create a route
ROUTE_CREATED=$(aws ec2 create-route \
    --route-table-id $ROUTE_TABLE_ID\
    --destination-cidr-block 0.0.0.0/0 \
    --gateway-id $IGW_ID
)
echo "ROUTE CREATED $ROUTE_CREATED"

# associate subnet explicitly
ASSOCIATION_ID=$(aws ec2 associate-route-table \
--route-table-id $ROUTE_TABLE_ID \
--subnet-id $SUBNET_ID \
--query AssociationId \
--output text
 )
ASSOC_ID=$(aws ec2 describe-route-tables --route-table-id "$ROUTE_TABLE_ID" --query "RouteTables[*].Associations[?SubnetId=='$SUBNET_ID'].AssociationId" --output text
) 
# ASSOCIATION_ID=$(aws ec2 describe-route-tables --route-table-id "$ROUTE_TABLE_ID" --query "RouteTables[*].Associations[?SubnetId=='$SUBNET_ID'].AssociationId" --output text)

echo "ROUTE ASSOCIATED_ID $ASSOCIATION_ID"
echo "ROUTE ASSOC_ID $ASSOC_ID"
# add route for route table to IGW
# ASSOCIATION_ID=$(aws ec2 associate-route-table \
# --route-table-id $ROUTE_TABLE_ID \
# --subnet-id $SUBNET_ID \
# --query Association.AssociationId \
# --output text
# )
# echo "ROUTE ASSOCIATED $ASSOCIATION_ID"

echo "./delete_vpc $VPC_ID $IGW_ID $SUBNET_ID $ROUTE_TABLE_ID $ASSOCIATION_ID"