#! /usr/bin/env bash
echo "====create-VPC==="
if [ -z "$1" ]; then
    echo "no VPC NAME given."
    exit 1
fi
VPC_NAME=$1

# create our vpc
VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" \
--region ca-central-1 \
--tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=$VPC_NAME}]" \
--query Vpc.VpcId \
--output text)

echo "VPC ID is $VPC_ID"


# create IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text
)

echo "IGW ID is $IGW_ID"
# attach the IGW
aws ec2 attach-internet-gateway \
--internet-gateway-id "$IGW_ID" \
--vpc-id "$VPC_ID"
# create subnet

# associate subnet explicitly

# add route for route table to IGW