#! /usr/bin/env bash

# create our vpc
VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" \
--region ca-central-1 \
--tag-specifications ResourceType=vpc,Tags='[{Key=Name,Value="my-vpc-3"}]' \
--query Vpc.VpcId \
--output text)
# create IGW

# attach the IGW

# create subnet

# associate subnet explicitly

# add route for route table to IGW