#! /usr/bin/env bash
echo "====put-object==="
if [ -z "$1" ]; then
    echo "no bucket name given."
    echo "there needs tpo be a bucket name. EG: ./put-obnject my-bucket-name fprefix"
    exit 1
fi
# check for filename
if [ -z "$2" ]; then
    echo "no second param name given."
    echo "there needs to be a file name. EG: ./put-obnject my-bucket-name filename"
    exit 1
fi
BUCKET_NAME=$1
FILENAME=$2

# Extract the filename (without the directory)
filename=$(basename "$FILENAME")

# Extract the extension
extension="${filename##*.}"

# Extract the filename without the extension
filename_without_extension="${filename%.*}"

aws s3api put-object \
--bucket $BUCKET_NAME \
--key $filename \
--body $FILENAME
